# Logistic Regression Algorithm

In [1]:
#importing laibrays

import numpy as np
import pandas as pd


In [2]:
#loading dataset

df = pd.read_csv("F:/ml_assets/logistic_algo_preactice.csv")
df

age  status
0    18       1
1    16       0
2    21       1
3    23       1
4    16       0
5    17       0
6    27       1
7    29       1
8    14       0
9    17       0
10   33       1
11   13       0
12   21       1
13   22       1
14   15       0
15   17       0
16   19       1
17   15       0
18   20       1
19   15       0
20   34       1
21   17       0
22   28       1

In [3]:
#checking null values

df.isnull().sum()

age       0
status    0
dtype: int64

In [4]:
df['status'].value_counts()

1    12
0    11
Name: status, dtype: int64

In [5]:
#seperiting x y

x = df[['age']]
x

age
0    18
1    16
2    21
3    23
4    16
5    17
6    27
7    29
8    14
9    17
10   33
11   13
12   21
13   22
14   15
15   17
16   19
17   15
18   20
19   15
20   34
21   17
22   28

In [6]:
y = df['status']
y

0     1
1     0
2     1
3     1
4     0
5     0
6     1
7     1
8     0
9     0
10    1
11    0
12    1
13    1
14    0
15    0
16    1
17    0
18    1
19    0
20    1
21    0
22    1
Name: status, dtype: int64

In [7]:
#traning and spliting

from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=.30,random_state=2)

In [8]:
xtrain

age
12   21
9    17
4    16
10   33
5    17
17   15
1    16
2    21
7    29
19   15
18   20
11   13
22   28
13   22
15   17
8    14

In [9]:
xtest

age
20   34
0    18
21   17
6    27
14   15
16   19
3    23

In [10]:
ytrain

12    1
9     0
4     0
10    1
5     0
17    0
1     0
2     1
7     1
19    0
18    1
11    0
22    1
13    1
15    0
8     0
Name: status, dtype: int64

In [11]:
ytest

20    1
0     1
21    0
6     1
14    0
16    1
3     1
Name: status, dtype: int64

In [12]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

In [13]:
model.fit(xtrain,ytrain)

LogisticRegression()

In [14]:
model.predict(xtest)

array([1, 0, 0, 1, 0, 1, 1], dtype=int64)

In [16]:
model.score(xtest,ytest)*100

85.71428571428571

In [18]:
model.predict_proba(xtest)

array([[5.08708831e-09, 9.99999995e-01],
       [7.46207564e-01, 2.53792436e-01],
       [9.12090192e-01, 8.79098083e-02],
       [3.46569701e-05, 9.99965343e-01],
       [9.92319103e-01, 7.68089693e-03],
       [4.54512764e-01, 5.45487236e-01],
       [5.34510195e-03, 9.94654898e-01]])

In [29]:
p = 21
model.predict([[p]])

C:\anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)