In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.read_csv("F:/ml_assets/spamham.csv")
df.head()

Text  Class Label
0  Supply Quality China's EXCLUSIVE dimensions at...      1  spam
1                         over. SidLet me know. Thx.      0   ham
2  Dear Friend,Greetings to you.I wish to accost ...      1  spam
3  MR. CHEUNG PUIHANG SENG BANK LTD.DES VOEUX RD....      1  spam
4          Not a surprising assessment from Embassy.      0   ham

In [3]:
df.Class.shape


(4845,)

In [4]:
df.Text.shape

(4845,)

In [5]:
data  = df[['Text','Class']]
data

Text  Class
0     Supply Quality China's EXCLUSIVE dimensions at...      1
1                            over. SidLet me know. Thx.      0
2     Dear Friend,Greetings to you.I wish to accost ...      1
3     MR. CHEUNG PUIHANG SENG BANK LTD.DES VOEUX RD....      1
4             Not a surprising assessment from Embassy.      0
...                                                 ...    ...
4840  It has been prepared- ready for your signature...      0
4841                                     And to you too      0
4842   <html><head><style>P{margin:0px;padding:0px}body      1
4843  Robinson talking now voice cracking but resolu...      0
4844  PIR <preines(Wednesday February 10 2010 1:16 P...      0

[4845 rows x 2 columns]

In [6]:
#checking null value

data.isnull().sum()

Text     0
Class    0
dtype: int64

In [7]:
data["Class"].value_counts()

0    2732
1    2113
Name: Class, dtype: int64

# X , Y Sepliting

In [8]:
x = data.Text.values


In [9]:
y = data.Class.values

# Training and Testing Data

In [10]:
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.3, random_state=2)

# Data Preprocessing

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
x_train = cv.fit_transform(xtrain)

In [12]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [13]:
x_train.shape

(3391, 45835)

In [14]:
ytrain.shape

(3391,)

# ML Algorithm

In [15]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x_train,ytrain)

MultinomialNB()

In [16]:
x_test = cv.transform(xtest)
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [17]:
model.score(x_test,ytest)*100

95.46079779917468

In [24]:
emails = ['hello i am seasun']
cv_emails = cv.transform(emails)
cv_emails.dtype

dtype('int64')

In [23]:
model.predict(cv_emails)

array([1], dtype=int64)

In [21]:
import pickle as pk

pk.dump(model,open('navie_bayes_classification.pkl','wb'))
